### ISSUE TITLE
Remove the stretch exception

### ISSUE THREAD

**Issue by benjamin-demarteau** [UnderGreen/ansible-role-mongodb#112]
This role seems to do shenningans to stretch which don't seem necessary anymore. Official MongoDB packages are provided for debian 9.

The only error I got was
```
unable to connect to database: Another user is already authenticated to this database. You must logout first
```
which is related to the `mongodb_user_fixed` task not calling logout at the end of its tasks.

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_BJ24IA/ansible_module_mongodb_user_fixed.py", line 419, in main
    client.admin.authenticate(login_user, login_password, source=login_database)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 1274, in authenticate
    connect=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 604, in _cache_credentials
    raise OperationFailure('Another user is already authenticated '
OperationFailure: Another user is already authenticated to this database. You must logout first.

failed: [ddd] (item={'name': 'nnn', 'password': 'xxx', 'roles': 'dbAdmin', 'database': 'ddd'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "database": "ddd",
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": "27017",
            "login_user": "siteUserAdmin",
            "name": "nnn",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "replica_set": null,
            "roles": [
                "dbAdmin"
            ],
            "ssl": false,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "state": "present",
            "update_password": "on_create"
        }
    },
    "item": {
        "database": "ddd",
        "name": "nnn",
        "password": "xxx",
        "roles": "dbAdmin"
    },
    "msg": "unable to connect to database: Another user is already authenticated to this database. You must logout first."
}
```

**Comment by legendetm** [comment]
But still, it would be nice to remove Stretch exceptions, because MongoDB supports Stretch, and deploy with Debian configuration worked.

**Comment by benjamin-demarteau** [comment]
Even worse, the deploy didn't work until I removed the exception.
